### ISSUE TITLE
sqlcmd needs to search x86 program files

### ISSUE THREAD

**Issue by mxriverlynn** [mxriverlynn/Albacore#102]
need to have sqlcmd search for the executable in the "Program Files (x86)" folder as well as "Program Files", to account for x64 Windows machines

**Comment by mxriverlynn** [comment]
also need to clean up how / where the search is done to make it easier to work with / understand when reading it.

**Comment by brettveenstra** [comment]
Path is usually updated when SqlCmd is installed, but it would be great to check for the file

**Comment by mxriverlynn** [comment]
this is done and in the dev branch now.
