### ISSUE TITLE
Warning when calling rake

### ISSUE THREAD

**Issue by badjer** [mxriverlynn/Albacore#107]
Requiring albacore in a rakefile generates a warning:
.../1.8/gems/albacore-0.1.5/lib/albacore/support/attrmethods.rb:7: warning: parenthesize argument(s) for future version

Changing line 7 of /lib/albacore/support/attrmethods.rb from this:
    return instance_variable_get "@#{n}"
to this:
    return instance_variable_get("@#{n}")
resolves the issue.

**Comment by mxriverlynn** [comment]
this is done in v0.2.0, which should be finalized / released soon.
