### ISSUE TITLE
xUnit.net task and Hudson CI

### ISSUE THREAD

**Issue by prabirshrestha** [mxriverlynn/Albacore#109]
seems like there is a small bug in xunit test runner.

under windows, mingw32 bash prompt this would work fine, but when i run in Hudoson CI, i gives error.
Lets say I have a project in hudson called "Hello World" (note: there is a space)
so in hudson it would create a directory called C:\hudson\jobs\Hello World\workspace and download the source from there.

so when i run the albacore xunit.net task in hudson, it would fail. following is the console output from Hudson

Time Elapsed 00:00:37.05
xUnit.net console test runner (32-bit .NET 2.0.50727.3615)
Copyright (C) 2007-9 Microsoft Corporation.

error: unknown option: World/workspace/bin/Tests/Hello.World.Tests.dll.html
rake aborted!
XUnit Failed. See Build Log For Detail

It seems that the space would make it assume its a different command line option.

after checking  xunit test runner, i soon fixed the bug. 
\"#{

seems like we need to add a quote in start and end of the path so that it would consider as one option.

 def build_html_output  
    fail_with_message 'Directory is required for html_output' if !File.directory?(File.expand_path(@html_output))
    "/html \"#{File.join(File.expand_path(@html_output),"%s.html")}\""  
  end

Time Elapsed 00:00:36.82
xUnit.net console test runner (32-bit .NET 2.0.50727.3615)
Copyright (C) 2007-9 Microsoft Corporation.

xunit.dll:     Version 1.5.0.1479
Test assembly: c:\hudson\jobs\Hello World\workspace\bin\Release\Hello.World.Tests.dll

So now it works and recognizes it as an assembly.

not sure if this is the problem with nunit too.

I'm running hudson in windows server 2008.

i have fixed it and will send you the pull request soon.

albacore v0.2.0preview

**Comment by mxriverlynn** [comment]
fixed... will be in the v0.2.0 release
