### ISSUE TITLE
ilmerge task

### ISSUE THREAD

**Issue by prabirshrestha** [mxriverlynn/Albacore#116]
create ilmerge task

**Comment by tkellogg** [comment]
+1 I had to create an IL merge task by hand a while ago. Not that it's hard, but still...

**Comment by haf** [comment]
Care to make a pull request with that task?

**Comment by tkellogg** [comment]
@haf - I had to clean up the code because it was in a state where I'd be embarrassed to open source it. Hopefully this will work...

**Comment by haf** [comment]
We have the actual pull request in the issue tracker, so closing this issue.
