### ISSUE TITLE
Ruby 1.9.2 Support

### ISSUE THREAD

**Issue by AndrewVos** [mxriverlynn/Albacore#117]
I recently forked this project in an an attempt to try and add devenv.exe build support (some projects need to be built using devenv).

I noticed that a whole lot of were failing to require other files because Ruby 1.9.2 doesn't add . to the current load path by default.

Is there some sort of strategy for changing this to support 1.9.2? Any ideas?

**Comment by mxriverlynn** [comment]
have been working on this recently. hoping to have it fixed up and working w/ 1.9.2 soon. 

i think for now, you can do this at the top of your rakefile: <code>$: "./"</code>

i haven't verified that, yet... but if the . path is not in teh loadpath, that should work.

**Comment by AndrewVos** [comment]
Yes that does sound about right.

I was trying to add "." as a temporary workaround, just assuming that there would be a File.join done on the parameter put into the require call. I don't think this worked though. It might be that fact that all ruby files would need to add . to the load path.

Either way, thanks!
