### ISSUE TITLE
NDepend and absolute paths issue

### ISSUE THREAD

**Issue by mxriverlynn** [mxriverlynn/Albacore#118]
## from the mailing list...

I'm a complete newbie to Ruby, though have run this problem past a
colleague who is a reasonably experienced Ruby developer, and between
us we can't figure this one out. Trying to get NDepend running via a
bit of rake/ruby:

```
ndepend = NDepend.new
ndepend.path_to_command = 'C:\tools\ndepend\NDepend.Console.exe'
ndepend.project_file =  'c:\src\Trunk\myproject.ndproj'
ndepend.run
```

Gives the error:
Bad command line arguments: Cannot extract path for NDepend project
path or invalid option {C:/src/Trunk/myproject.ndproj}   Reason:The
absolute path doesn't begin with a single letter drive followed by ":
\"

I can't figure out why the slashes are being switched from back
slashes, in the error message, to forward slashes. Or even if this is
the correct way to call it. NDepend has created the .ndproj file, but
the examples I've seen on the web always refer to .xml files for the
project filename.

Any ideas?

Col

---

it's the call to File.expand_path(@project_file) in the NDepend object. need to figure out why this is there, and see what it takes to remove the expand_path call.

**Comment by haf** [comment]
Still an issue?

**Comment by mxriverlynn** [comment]
i haven't heard anyone else saying they are having issues since i originally put this in here. closing.

**Comment by atahir** [comment]
I have also found this to be an issue. NDepend.console.exe does not work with forward slashes. 

The File.expand_path seems to replace all the '\' with '/'
