### ISSUE TITLE
Create a task for fluent migrator

### ISSUE THREAD

**Issue by minhajuddin** [mxriverlynn/Albacore#122]
I already have an unstructured rake file with all the tasks, Will clean it up and commit on my fork.

**Comment by mxriverlynn** [comment]
sounds good. be sure to check out the Custom Tasks wiki page, if you haven't done so already. it describes how to create your own task for 0.2.x release

https://github.com/derickbailey/Albacore/wiki/Custom-Tasks

**Comment by mxriverlynn** [comment]
did you ever submit a pull request for this? i see a fluentmigrator task in the dev branch now, but it's from a guy named Mark Bultoc.

**Comment by mxriverlynn** [comment]
there's a task in the dev branch now.
