### ISSUE TITLE
Pure Ruby schema validation options?

### ISSUE THREAD

**Issue by stevehebert** [mxriverlynn/Albacore#133]
I rewrote the nuspec task using the rexml library instead of nokogiri - giving us compatibility with IronRuby 1.0.

However for testing I'm also validating the xml output of the task with the nuspec xsd file created by microsoft using nokogiri.  Rexml does not have schema validation.  Does anyone know of a ruby library that does xml schema validation and it works with IronRuby?

**Comment by mxriverlynn** [comment]
i'm having a hard time finding a ruby xml gem that works with ironruby 1.0, unfortunately. are there any other options?

**Comment by mxriverlynn** [comment]
we solved this with an ironruby specific validation vs rubyinstaller validation. it's all in the dev branch now
