### ISSUE TITLE
Upgrade to RSpec 2.x

### ISSUE THREAD

**Issue by mxriverlynn** [mxriverlynn/Albacore#139]
i tried in the Dev branch, before the 0.2.3 release... but it broke all kinds of stuff and i didn't understand why, so i reverted back to 1.2.9 for the 0.2.3 release of albacore. i'd like to move forward though. maybe for the 0.3.0 release.

**Comment by haf** [comment]
Done with my pull requests.

**Comment by haf** [comment]
As stated, done and merged.

**Comment by mxriverlynn** [comment]
Re-opening this as the rake tasks are now failing. The updated 2.x line of RSpec has a different file structure, and renamed a lot of things that were previously used.

**Comment by haf** [comment]
Could you provide a wiki page with the prerequisites for testing everything? NCover executable download location etc?

**Comment by haf** [comment]
Done now.
