### ISSUE TITLE
Nuspec File Target Bug

### ISSUE THREAD

**Issue by mikeobrien** [mxriverlynn/Albacore#142]
Looks like there is a bug at nuspec.rb:11:

depend.add_attribute( 'target', @target ) if @target.to_s == 0

The task will not set the target attribute and I think it is because of the "@target.to_s == 0". I think it should be "!@target.nil?" but I have only a passing knowledge of ruby so I may be off here.

**Comment by mikeobrien** [comment]
Actually, I just realized that you don't have to specify the files in the nuspec if you just follow the path conventions. So this will not be an issue for those following the convention.

**Comment by mxriverlynn** [comment]
thanks for the tip on this, brian. can you post the task configuration that you were using, when the error happened? i'll be sure to get a test written around this and get it fixed asap.

**Comment by mikeobrien** [comment]
It was along the lines of this:

desc "Create the nuspec"
nuspec :createSpec => :unitTests do |nuspec|
   #...
   nuspec.file("src/Yada/bin/Release/Yada.dll", "lib")
end

Thanks,

m

**Comment by mxriverlynn** [comment]
fixed issues with nuspec files / targets. closed by 861dc4348b4dc3cd57efa107f76b98e337547e4e
