### ISSUE TITLE
nuspec task generated title tag opposed to xsd

### ISSUE THREAD

**Issue by haf** [mxriverlynn/Albacore#148]
http://nuget.codeplex.com/SourceControl/changeset/view/e6f7bea8df68#NuPack.Core%2fAuthoring%2fnuspec.xsd

The nuget xsd doesn't specify a title tag. If I don't set the title property, an empty tag contradictory to the xsd is still generated. Hence I can't use nuspec tasks to generate nuspecs.

**Comment by mxriverlynn** [comment]
noticed you closed the issue before i could look into this... is it not really an issue? or did you find a solution?

**Comment by haf** [comment]
Sorry for the churn, it was because I was reading an old xsd linked from the wiki and on top of that had an old binary that validated against that old xsd... :) My mistake.

**Comment by mxriverlynn** [comment]
no problem. glad you got things figured out. :) 

i'll take a look at your pull request hopefully some time this week. swamped trying to get a project out the door for a client, though, so no promised at the moment.
