### ISSUE TITLE
AssemblyInfo deletes not specified attributes

### ISSUE THREAD

**Issue by Andreone** [mxriverlynn/Albacore#155]
Hi,

I'm using Albacore 0.2.5 with ruby 1.9.2.

Given an assemblyinfo.cs like this

using System.Reflection;
using System.Runtime.InteropServices;
[assembly: AssemblyTitle("Project")]
[assembly: AssemblyDescription("balh blah")]
[assembly: AssemblyVersion("0.0.0.0")]
[assembly: AssemblyFileVersion("0.0.0.0")]

running this task

assemblyinfo :versioning do |t|
    t.version = '1.0.0.0'
    t.file_version = '1.0.0.0'
    t.output_file = assemblyinfo.cs
end

results in an assemblyinfo.cs like this:

using System.Reflection;
using System.Runtime.InteropServices;
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]

Shouldn't the title and description attributes still be present?

**Comment by mxriverlynn** [comment]
if you specify your existing assembly info file as the .input_file to the asm task, it will work this way.

```
assemblyinfo do |asm|
  asm.input_file = "existing\assemblyinfo.cs"
  # ... other settings
end
```

... however...

best practice is to keep the assembly attributes that are generated by the build tool in a separate file, and to leave the project specific or non-generated attributes in the original file. this is typically done by creating an "assemblyinfo.cs" file at the root of your solution folder, and then each of the projects in your solution would add a link to this file. that way you only need to generate one assembly info file for your entire system, but each project in the solution can still have it's own project-specific information, such as the title and description.

**Comment by Andreone** [comment]
Thanks. I did look in the wiki but input_file was not mentioned. I've added a section for it.
