### ISSUE TITLE
Hidden dependency on RubyZip

### ISSUE THREAD

**Issue by Maxim-Filimonov** [mxriverlynn/Albacore#158]
I've recently started to use albacore but from the beginning found getting started and wiki are not really correct or something was changed recently which requires a bit different steps to get started. 
I've installed ruby using RubyInstaller and install rake and albacore but when I put require 'albacore' on top of my rakefile rake throws an error. After a bit of searching I found a solution http://webcache.googleusercontent.com/search?q=cache:http://www.tigraine.at/2011/06/30/missing-zip-zip-from-albacore/
But I believe that the problem should be either mentioned in wiki or solved by introducing gem dependency to albacore. I'm not planning to use zip task but if it's required by albacore it's better to have it in dependency.

**Comment by mxriverlynn** [comment]
hi - i've updated the documentation in the getting started page to include a note on installing rubyzip, if it did not come down automatically.

it appears that newer versions of the rubygem spec have changed the way dependencies are noted, or i just broke my gemspec when i built the v0.2.6 release. i'll get the gem fixed and uploaded again so that it pulls down automatically, again.

thanks

**Comment by haf** [comment]
Any news on this? The workaround doesn't work for me, even if I install rubyzip.

**Comment by mxriverlynn** [comment]
are you getting the same "no such file to load -- rubyzip" error or something else?

i have not yet had a chance to look into fixing the gem file.

**Comment by haf** [comment]
Sometimes I get 'cannot load file zip/zip'
From requires ...

It's not solvable by restarting the prompt - I have to downgrade albacore.

-----Original Message-----

**Comment by haf** [comment]
A push of a new version would be great.

**Comment by mxriverlynn** [comment]
I've corrected the gemspec, rebuilt the gem and pushed albacore v0.2.7 up to rubygems.org. the dependency should be good now.
