### ISSUE TITLE
add additional language options for assembly info generator

### ISSUE THREAD

**Issue by mxriverlynn** [mxriverlynn/Albacore#16]
should add additional language options for assembly info generator. probably want to follow the same pattern as the 'testrunner' stuff in the ncoverconsoletask, and allow a language specific object to be assigned to the assemblyinfo object. this would allow for easy extension of the generator, to provide implementations in different languages, such as vb.net

**Comment by markwilk** [comment]
derick:

This has been added.

Mark

**Comment by mxriverlynn** [comment]
i've pulled these changes into the Dev branch. thanks, Mark!
