### ISSUE TITLE
When using /m MSBuild parameter, extra MSBuild.exe processes left behind

### ISSUE THREAD

**Issue by mkmurray** [mxriverlynn/Albacore#161]
When trying to parallelize a build [using some tips from a Scott Hanselman blog post](http://www.hanselman.com/blog/FasterBuildsWithMSBuildUsingParallelBuildsAndMulticoreCPUs.aspx) (specifically using the `/m` command line flag), it leaves behind N-1 `MSBuild.exe` processes running on your machine (where N is the number of logical cores of your machine). I assume it's because the other MSBuild processes are out of Albacore's hand, as it only knows about the one process it kicked off? Anything that can be done to remedy this?

**Comment by mxriverlynn** [comment]
i'm not familiar with the /m option. have you tried running this from the command line directly to see what happens? i'd be interested in knowing if the same behavior occurs. 

in the end, the msbuild task (and the other command line tool tasks) just execute whatever tool it is via the command line for that tool. this makes me think it's an msbuild issue and not a ruby / rake / albacore issue. but i could be wrong. perhaps there's something else going on that i don't understand yet.

**Comment by developingchris** [comment]
I have an example, that this is the behavior of msbuild.exe when run just from a batch file as well. It seems like a strange switch, unless you have more projects than you have cores.

When I run the build for a single kata, 2 assemblies, I get 8 msbuilds, 7 orphaned.

**Comment by mkmurray** [comment]
Chris, I appreciate you looking into this running outside of albacore (I was gonna try to get to it sometime). We have several more projects than we have cores, so it is a significant performance increase. Glad to know it's not albacore, I suspected it could be MS (it always is). I looked back later in the day and the processes were gone, so perhaps they're just slow to clean up. Thanks!

**Comment by developingchris** [comment]
you can always do an exec 'taskmanager /f /im "msbuild.exe"' on success of the build

**Comment by jdh28** [comment]
Just in case anyone comes across this again, I found a similar issue with msbuild. You can fix it by passing /nr:false to msbuild.
