### ISSUE TITLE
NuGetPush - Support setting target server

### ISSUE THREAD

**Issue by jimitndiaye** [mxriverlynn/Albacore#162]
NuGetPush doesn't not currently support pushing NuGet galleries other than NuGet.org

**Comment by prabirshrestha** [comment]
this is already supported. you will need to set "source"

https://github.com/derickbailey/Albacore/blob/dev/lib/albacore/nugetpush.rb#L14

```
nugetpush :nuget_push do |nuget|
    nuget.command = "nuget.exe"
    nuget.package = "Facebook.5.0.25.0.nupkg"
    nuget.apikey = "...."
    nuget.source = "http://nuget.gw.symbolsource.org/Public/Nuget"
    nuget.create_only = false
end
```

make sure the check the wiki https://github.com/derickbailey/Albacore/wiki/NugetPush-Task

**Comment by jimitndiaye** [comment]
I thought that was to set the symbol source server, rather than the
package gallery server.

Sent from my iPhone

On 25 Jul 2011, at 15:29, prabirshrestha
reply@reply.github.com
wrote:

**Comment by prabirshrestha** [comment]
if you don't set source, nuget.exe chooses the default one.

if you do set source, you override the default source of nuget.exe, this can be symbol source or your own.

**Comment by haf** [comment]
ok, closing this one.
