### ISSUE TITLE
0.2.6 dependencies omit rubyzip?

### ISSUE THREAD

**Issue by PandaWood** [mxriverlynn/Albacore#163]
I was just wondering if this was a problem with the dependencies with 0.2.6. I haven't investigated this much, apologies:

If I upgrade to albacore 0.2.6 via bundler, I get this message, but then I can't build - see the message re zip/zip below
    Installing albacore (0.2.6)

But if I switch to albacore 0.2.3/4 or 5 via bundler, I see this message & then everything works
    Using rubyzip (0.9.4)
    Installing albacore (0.2.3)

This error only happens after upgrading to 0.2.6

no such file to load -- zip/zip
C:/Projects/build/bundler/ruby/1.9.1/gems/albacore-0.2.6/lib/albacore/unzip.rb:2:in `require'
C:/Projects/build/bundler/ruby/1.9.1/gems/albacore-0.2.6/lib/albacore/unzip.rb:2:in`<top (required)>'
C:/Projects/build/bundler/ruby/1.9.1/gems/albacore-0.2.6/lib/albacore.rb:9:in `require'
C:/Projects/build/bundler/ruby/1.9.1/gems/albacore-0.2.6/lib/albacore.rb:9:in`block in <top (required)>'
C:/Projects/build/bundler/ruby/1.9.1/gems/albacore-0.2.6/lib/albacore.rb:9:in `each'
C:/Projects/build/bundler/ruby/1.9.1/gems/albacore-0.2.6/lib/albacore.rb:9:in`<top (required)>'
C:/Projects/build/rake/main.rb:4:in `require'
C:/Projects/build/rake/main.rb:4:in`<top (required)>'
internal:lib/rubygems/custom_require:29:in `require'
<internal:lib/rubygems/custom_require>:29:in`require'
C:/Projects/Rakefile.rb:1:in `<top (required)>'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:2373:in`load'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:2373:in `raw_load_rakefile'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:2007:in`block in load_rakefile'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:2058:in `standard_exception_handling'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:2006:in`load_rakefile'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:1991:in `run'

**Comment by mxriverlynn** [comment]
this was an error in the gemspec for 0.2.6. update to 0.2.7 and it is fixed
