### ISSUE TITLE
Global access to Rake DSL methods is deprecated

### ISSUE THREAD

**Issue by pontusm** [mxriverlynn/Albacore#165]
Hi,

I'm getting the following warning when using the "output" task:

`WARNING: Global access to Rake DSL methods is deprecated.  Please include    ...  Rake::DSL into classes and modules which use the Rake DSL methods.
WARNING: DSL method Class#rmtree called at C:/Ruby192/lib/ruby/gems/1.9.1/gems/albacore-0.2.7/lib/albacore/output.rb:35:in 'output_to'
WARNING: DSL method Class#mkdir called at C:/Ruby192/lib/ruby/gems/1.9.1/gems/albacore-0.2.7/lib/albacore/output.rb:36:in 'output_to'`

I think it can be fixed by just inserting this in the class:

```
include Rake::DSL
```

**Comment by haf** [comment]
Care to wrap up a pull request for this against /dev branch?

**Comment by pontusm** [comment]
Sure I can take a look at it.

**Comment by haf** [comment]
Fixed, thanks for your pull request.
