### ISSUE TITLE
Exluding projects in the MSBuild task

### ISSUE THREAD

**Issue by schwarz** [mxriverlynn/Albacore#196]
I currently have two projects in the same solution, on being the test suite. How can I exclude that project in the MSBuild task?

**Comment by mxriverlynn** [comment]
The usual method for excluding a project is to create a build configuration within visual studio that doesn't build it. If you look at the "Debug" and "Release" mode drop down list, you'll find an option that brings up a dialog box. In this, you can tell the solution which projects to build for which configuration. Typically you would set the test project to not build in release mode, and then have your rake tasks set up to build the solution in release mode. This will prevent the test project from being built.

**Comment by schwarz** [comment]
I didn't even know about this. Thank you!
