### ISSUE TITLE
comma-separated nowarn property gives error in msbuild

### ISSUE THREAD

**Issue by mikebridge** [mxriverlynn/Albacore#207]
I have the following task set up for running msbuild. This works OK:

``` ruby
namespace :build do      
  desc "Build for debug"            
  msbuild :debug => ["js:min", :less, WEBAPPBINDIR] do |msb|
    msb.properties = { :configuration => :DebugAll, :nowarn => "0105" }
    msb.targets :Clean, :Build
    msb.solution = absolute_path("MySolution.sln")
  end
end
```

But when I add a second warning to :nowarn, it fails with the msbuild error:

`MSBuild Failed. See Build Log For Detail`

and

`MSBUILD : error MSB1006: Property is not valid.`

``` ruby
  desc "Build for debug"            
  msbuild :debug => ["js:min", :less, WEBAPPBINDIR] do |msb|
    # NOTE EXTRA WARNING HERE:
    msb.properties = { :configuration => :DebugAll, :nowarn => "0105,0108" }
    msb.targets :Clean, :Build
    msb.solution = absolute_path("MySolution.sln")
  end
```

Strangely, the command that's produced by albacore works ok when I bypass rake and run it from the command line:

``` bat
> "C:/Windows/Microsoft.NET/Framework/v4.0.30319/MSBuild.exe" "C:/blah/MySolution.sln" /p:configuration="DebugAll" /p:nowarn="0105,0108" "/target:Clean;Build"
```

I'm running this with JRuby 1.6.5.

Any idea why that isn't working?

Thanks!

**Comment by mikebridge** [comment]
Sorry, I see the workaround / solution to this is to use a space instead of a comma:

  `:nowarn => "0105 0108"`

**Comment by haf** [comment]
If you would document this in the wiki, that would be awesome :).

**Comment by mikebridge** [comment]
No problem, I can do that.

Just to follow up, the commas work fine in IronRuby, but not in JRuby 1.6.5.

**Comment by mikebridge** [comment]
In case this helps anyone in the future, I am encountering a similar incompatibility between IronRuby and JRuby here:

``` ruby
def to_win(file) 
    file.gsub(%r{/}) { "\\" }
end

exec :buildfile, :src, :dest do |cmd, args| 
        raise "ERROR: :src must be defined" if args[:src].nil?
        raise "ERROR: :dest must be defined" if args[:dest].nil?
        cmd.command = "#{SOLUTIONDIR}\\Tools\\dotless-v1.3.0.3\\dotless.Compiler"       
        cmd.parameters = "-m -r \"#{to_win(args[:src])}\" \"#{to_win(args[:dest])}\""
end
```

This produces this output on both JRuby and IronRuby:

``` bat
Executing Exec: "C:\Visual Studio 2010\Projects\MySolution\Tools\dotless-v1.3.0.3\dotless.Compiler" -m -r
 "C:\Visual Studio 2010\Projects\MySolution\WebApp\Content\less\myfile.less" "C:\Visual Studio 2010\Projects\MySolution\WebApp\Content\css\myfile.css"
```

Albacore on JRuby doesn't have a problem with it, but IronRuby fails with a rather ambiguous "Exec Failed" error.

My workaround: don't use IronRuby.

**Comment by haf** [comment]
Thank you Mike. Closing the issue.
