### ISSUE TITLE
NugetPush unable to find package

### ISSUE THREAD

**Issue by worldspawn** [mxriverlynn/Albacore#218]
I wrote this task

```
nugetpush :nuget_push, [:apikey] => [:prepbuild, :buildIt, :packageIt] do |nuget, args|
    FileUtils.copy_file('./src/.nuget/NuGet.exe', File.join('./build/package/','NuGet.exe'))
    nuget.command     = "./build/package/nuget.exe"
    nuget.package = "StackExchange.Profiling.Nhibernate.2.0.2.0.nupkg"
    nuget.apikey = args[:apikey]
end
```

I just get:
File does not exist (StackExchange.Profiling.Nhibernate.2.0.2.0.nupkg). 

all the time. I'm copying nuget.exe into the same folder as the package as I thought might solve it but no it is still unable to find the package. As far as I can tell this only works if nuget.exe is in the same folder as the rakefile and the nupkg.

**Comment by worldspawn** [comment]
Actually this might just be an issue with nuget.exe. I'm getting the same (stupid) behaviour when i run nuget.exe directly from the command line.

**Comment by haf** [comment]
Tell me your results. I'm closing this in the mean-time.
