### ISSUE TITLE
Invoking targets from two msbuild files from the same rake task

### ISSUE THREAD

**Issue by schatekar** [mxriverlynn/Albacore#219]
This is not exactly a defect but could be a misunderstood feature

I have a msbuild task that needs to call into two different msbuild files. But that does not seem to work if I follow the documentation on wiki. The second msbuild target overrides the first one. 

Is there a way to achieve this?

**Comment by haf** [comment]
I think you aren't naming the tasks differently. Can you verify they are named different things?

**Comment by schatekar** [comment]
So you are suggesting, create two tasks, name them differently and a third task that calls these two?

**Comment by haf** [comment]
A third task that depends on the two, yes:

```
msbuild :a do ; end
msbuild :b do ; end
task :compile => [:a, :b]
```
