### ISSUE TITLE
Discuss dependencies in wiki

### ISSUE THREAD

**Issue by BenHall** [mxriverlynn/Albacore#26]
Happened to be mentioned by Steven Harman http://twitter.com/stevenharman/status/5931766258

Currently working on this script which will install all the required gems so you can use rake specs:all
http://github.com/BenHall/Albacore/blob/master/spec/install_dependencies.rb

This should be discussed within the wiki, along with a list of the dependencies.

**Comment by mxriverlynn** [comment]
moving the file to root of the repo and renaming to install_developer_dependencies; in my dev branch

**Comment by mxriverlynn** [comment]
errr - not renaming file. just moving it. also updated it so it checks for installed dependencies / gem source, to prevent errors. reports out to the console whether it found the item or is installing the item. currently in my dev branch. will be release in next version.

wiki page on "HowToContribute" was also added to discuss basic options and dependency stuff.
