### ISSUE TITLE
Create NAnt Task

### ISSUE THREAD

**Issue by stevenharman** [mxriverlynn/Albacore#27]
As a user moving to Rake, from an existing NAnt-based build solution, it would be nice to be able to move my build tasks one at a time, rather than having to make a wholesale switch. One way to enable this migration route is by providing a NAnt task which simply shells out to my existing NAnt build script to do the work. An example usage may look something like:

<pre><code>
Albacore::NAntTask.new(:myTaskName) do |nant|
  nant.build_file = "path/to/nant/build/file.build"
  nant.target = :nantTaskName
  nant.properties << "build.config=debug"
  nant.properties << "build.version=0.0.1"
end
</code></pre>

**Comment by mxriverlynn** [comment]
has been pulled into the dev branch. thanks, yo!
