### ISSUE TITLE
allow directory globs (folder/**/*) for ExpandTemplates

### ISSUE THREAD

**Issue by mxriverlynn** [mxriverlynn/Albacore#28]
should allow the .expand_files property use directory/file globs. this would allow all of the files in a specified folder / hiearchy of folders, to be expanded all at once.

example usage:

<pre><code>desc "Expand the web.config template for the correct environment"
Albacore::ExpandTemplatesTask.new(:templates) do |tmp|
    tmp.expand_files = {"sometemplatefolder/**/*" => "someoutputfolder/"}
    tmp.data_file = "template.data"
end
</code></pre>

question: should the folder hierarchy be maintained? so if a file is in sometemplatefolder/subfolder/ should it be output to someoutputfolder/subfolder/ ?

i would think yes, off-hand...

**Comment by mxriverlynn** [comment]
perhaps a <code>.expand_folders</code> should be used instead of <code>.expand_files</code> for the directory globs?

<pre><code>desc "Expand the web.config template for the correct environment"
Albacore::ExpandTemplatesTask.new(:templates) do |tmp|
    tmp.expand_folder = {"templatefolder/**/*" => "outputfolder/"}
    tmp.data_file = "template.data"
end
</code></pre>

**Comment by doxavore** [comment]
What about something that allowed us to maintain folder structure, and give the user some flexibility in the output:
<code><pre>desc "Expand the web.config template for the correct environment"
Albacore::ExpandTemplatesTask.new(:templates) do |tmp|
    tmp.expand_folder = {"templatefolder/*_/_.template" => Proc.new { |f| f.chomp(File.extname(f)) } }
    tmp.data_file = "template.data"
end</pre></code>

This would give us more flexibility and easily maintain folder structure. (Although I'm not crazy about the syntax, it captures the feature idea a little more?)

**Comment by mxriverlynn** [comment]
i like the idea and i see the need now that you point it out... i wonder if there's a better syntax that we can find, though. this is functional, but it's cryptic - it's not easy to know what it's doing or why.

perhaps the hash literal is not appropriate in this case. i used that originally because it gave the "input" => "output" sense... 

maybe something like this:

<pre><code>desc "Expand the web.config template for the correct environment"
Albacore::ExpandTemplatesTask.new(:templates) do |tmp|
    tmp.expand_folder = "templatefolder/**/*"
    tmp.filename_parser = Proc.new { |f| f.chomp(File.extname(f)) }
    tmp.data_file = "template.data"
end
</code></pre>


that's a little more clear, but still kinda ugly... how about a method block for renaming, without any other syntax noise around it:

<pre><code>desc "Expand the web.config template for the correct environment"
Albacore::ExpandTemplatesTask.new(:templates) do |tmp|
    tmp.expand_folder("templatefolder/**/*") { |f|  f.chomp(File.extname(f)) }
    tmp.data_file = "template.data"
end
</code></pre>

**Comment by doxavore** [comment]
There we are, I like the last syntax:

  tmp.expand_folder("templatefolder/*_/_") { |f|  f.chomp(File.extname(f)) }

Multiple calls to expand_folder should be supported, and if you like I'm pretty sure we could even support using them in combination:

  tmp.expand_folder("templatefolder1/**/*") { |f|  f.chomp(File.extname(f)) }
  tmp.expand_folder("templatefolder2/**/*") { |f|  f.chomp(File.extname(f)) }
  tmp.expand_folder = { "templatefolder/web.config.template" => "templateoutput/web.config" }

Internally, we'd maintain a hashmap like we did in my first comment, with the file name or glob as the first argument, and the file second argument a block or a string. I think this could be done without adding too much complexity to the class...?

**Comment by mxriverlynn** [comment]
how would we specify the output folder, in that scenario? we don't want to put the expanded files in the templatefolder...

perhaps a <code>tmp.output_folder = "output/folder/"</code> property?

also - i'd leave your last example usage for a specific file, as expand_files

<pre><code>
tmp.expand_folder("templatefolder/**/*") { |f| f.chomp(File.extname(f)) }
tmp.expand_folder("anotherfolder/**/*") { |f| f.chomp(File.extname(f)) }
tmp.output_folder = "output/folder"

tmp.expand_files = {"templatfolder/web.config.template" => "output/folder/web.config"}
</code></pre>

**Comment by doxavore** [comment]
The problem is keeping templates and output files separate isn't feasible for many projects. I have a solution that contains 5 different web apps, and to keep our buildfile and process for changing those templates simple it's much easier to put the template right where you're going to want the file (a web.config.template where you want your web.config). Deleting the template files from the staged output directory is simple, and there's never any question of which web.config file you're editing, which would become a little more hairy if you had to dig them out of a completely foreign folder structure.

I can see where a separate template folder would be helpful, but sometimes it's easiest to do more of an in-place replacement?

**Comment by mxriverlynn** [comment]
yeah, i understand what you're saying... but that's also the exact opposite of what the original author of this task said. :)

the option of specifying an output_folder has to be there. we could default it to the same folder as the template file, if none is given, and use output_folder as the root folder for the output, if one is given.

**Comment by mxriverlynn** [comment]
irrelevant now that expandtemplates has been killed. suggest using ERB or another existing template system

**Comment by MarkBorcherding** [comment]
Is it worth mentioning in the Wiki that we don't expect `expandtemplates` to be around in the next release? I agree ERB is better fit and mentioning that in the wiki might save people from start using `extendtemplates`.
