### ISSUE TITLE
create MSpecTestRunner

### ISSUE THREAD

**Issue by mxriverlynn** [mxriverlynn/Albacore#3]
Need to get @seanbiefeld's MSpecTestRunner imported into the repository, as a test runner for NCoverConsoleTask

**Comment by mxriverlynn** [comment]
merged @seanbiefeld's test runner, and added rspec test around it w/ ncoverconsole.

**Comment by BenHall** [comment]
This has been done now I think.... Or at least there is a MSpec test runner.

**Comment by mxriverlynn** [comment]
yup - done. thanks for closing it! i forgot.
