### ISSUE TITLE
Update README MsBuild Example

### ISSUE THREAD

**Issue by BenHall** [mxriverlynn/Albacore#31]
desc "Run a sample build using the MSBuildTask"
Albacore::MSBuildTask.new(:msbuild) do |msb|
    msb.properties :configuration => :Debug
    msb.targets [:Clean, :Build]
    msb.solution = "spec/support/TestSolution/TestSolution.sln"
end

Should be:

desc "Run a sample build using the MSBuildTask"
Albacore::MSBuildTask.new(:msbuild) do |msb|
    msb.properties = {:configuration => :Debug}
    msb.targets [:Clean, :Build]
    msb.solution = "spec/support/TestSolution/TestSolution.sln"
end

**Comment by mxriverlynn** [comment]
thanks, ben. fixed.
