### ISSUE TITLE
Can't find windows directory in cygwin

### ISSUE THREAD

**Issue by kevincolyar** [mxriverlynn/Albacore#4]
Get the following error when runing 'rake'

rake aborted!
can't dup NilClass
/cygdrive/c/Documents And Settings/kevinc/development/github/Albacore/lib/albacore/msbuild.rb:20:in `dup'

**Comment by kevincolyar** [comment]
Now looks in ENV['WINDIR'] when the windows directory is not found in ENV['windir'].

**Comment by mxriverlynn** [comment]
thanks, kevin! patch applied.
