### ISSUE TITLE
zip task needs to be able to ignore files

### ISSUE THREAD

**Issue by mxriverlynn** [mxriverlynn/Albacore#41]
need to use a file matching pattern and/or other syntax to allow certain files to be ignored. possibly something like this:

<pre><code>zip.include_files "**/*"
zip.exclude_files "ignore/me*"
</code></pre>

will need to think about the syntax a bit more. but that should get the idea across.

**Comment by jagregory** [comment]
I've got an impl. of this in my fork, but I wrote it before I saw your syntax suggestion. I can update it if you'd prefer.

Mine works like this:

```
zip.exclusions = [/some-regexp/, 'full-filepath']
```

**Comment by mxriverlynn** [comment]
let's start with what you have and see if we want to change, from there.

**Comment by mxriverlynn** [comment]
merged in james' changes, into the dev branch
