### ISSUE TITLE
msbuildtask targets doesn't work if you don't use an array

### ISSUE THREAD

**Issue by kberridge** [mxriverlynn/Albacore#46]
The msbuildtask wiki (http://wiki.github.com/derickbailey/Albacore/msbuildtask) says you should be able to do something like:
msb.targets :Rebuild

But this actually doesn't work.  You have to specify an array like msb.targets [:Rebuild].  Otherwise you get the following error:
*\* Invoke msbuild (first_time)
*\* Execute msbuild
rake aborted!
undefined method `join' for :Build:Symbol
C:/Ruby/lib/ruby/gems/1.8/gems/albacore-0.0.9/lib/albacore/msbuild.rb:56:in`build_targets'
C:/Ruby/lib/ruby/gems/1.8/gems/albacore-0.0.9/lib/albacore/msbuild.rb:41:in `build_solution'
C:/Ruby/lib/ruby/gems/1.8/gems/albacore-0.0.9/lib/albacore/msbuild.rb:31:in`build'
C:/Ruby/lib/ruby/gems/1.8/gems/albacore-0.0.9/lib/rake/msbuildtask.rb:12:in `execute'
C:/Ruby/lib/ruby/gems/1.8/gems/albacore-0.0.9/lib/rake/support/albacoretask.rb:15:in`define'
C:/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
C:/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`execute'
C:/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
C:/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`execute'
C:/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
C:/Ruby/lib/ruby/1.8/monitor.rb:242:in`synchronize'
C:/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
C:/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in`invoke'
C:/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
C:/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
C:/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
C:/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
C:/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
C:/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in`top_level'
C:/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
C:/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
C:/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
C:/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
C:/Ruby/bin/rake:19:in`load'
C:/Ruby/bin/rake:19

**Comment by mxriverlynn** [comment]
thanks for bringing this to our attention. i've got a fix in the 'dev' branch for this, which will be released as 0.1.0 sometime before the end of january. there's still some significant changes happening in the dev branch, so the fix may change... but i do have a test to prove the bug / fix, so it will be covered in the release.
