### ISSUE TITLE
NCover Console: Paths containing spaces

### ISSUE THREAD

**Issue by seanbiefeld** [mxriverlynn/Albacore#49]
the ncover console task cannot handle paths with spaces in the them when pointing to assemblies, if it finds a space it replaces it with " "
ncoverconsole.rb line 42:
result = run_command "NCover.Console", command_parameters.join(" ")

**Comment by mxriverlynn** [comment]
I'm unable to reproduce the issue. can you provide your rake task configuration?

**Comment by mxriverlynn** [comment]
i finally reproduced this. will be fixed in next release.

**Comment by mxriverlynn** [comment]
fixed and release in v0.1.2
