### ISSUE TITLE
Cygwin can't find Build command

### ISSUE THREAD

**Issue by kevincolyar** [mxriverlynn/Albacore#5]
I'm guessing cygwin can't find the msbuild 'Build' command when you try and build in cygwin.

I get the following error message when running

$ rake msbuild 
....  
 13 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.48
sh: Build: command not found

**Comment by mxriverlynn** [comment]
is the all the output you get? I'm not using the 'sh' command anywhere in Albacore.

**Comment by mxriverlynn** [comment]
here's the error I get when trying to run Albacore's rake file from cygwin:

<pre><code>
derickb@matdev09s /cygdrive/d/Dev/Derick-GitHub/Albacore
$ rake
(in /cygdrive/d/Dev/Derick-GitHub/Albacore)
/cygdrive/d/Dev/Derick-GitHub/Albacore/lib/spec/support/../../rake/assemblyinfot
ask.rb:1:in `require': no such file to load -- rake/tasklib (LoadError)
        from /cygdrive/d/Dev/Derick-GitHub/Albacore/lib/spec/support/../../rake/
assemblyinfotask.rb:1
        from ./lib/spec/assemblyinfotask_spec.rb:3:in `require'
        from ./lib/spec/assemblyinfotask_spec.rb:3
        from /usr/lib/ruby/gems/1.8/gems/rspec-1.2.8/lib/spec/runner/example_gro
up_runner.rb:15:in `load'
        from /usr/lib/ruby/gems/1.8/gems/rspec-1.2.8/lib/spec/runner/example_gro
up_runner.rb:15:in `load_files'
        from /usr/lib/ruby/gems/1.8/gems/rspec-1.2.8/lib/spec/runner/example_gro
up_runner.rb:14:in `each'
        from /usr/lib/ruby/gems/1.8/gems/rspec-1.2.8/lib/spec/runner/example_gro
up_runner.rb:14:in `load_files'
        from /usr/lib/ruby/gems/1.8/gems/rspec-1.2.8/lib/spec/runner/options.rb:
107:in `run_examples'
        from /usr/lib/ruby/gems/1.8/gems/rspec-1.2.8/lib/spec/runner/command_lin
e.rb:9:in `run'
        from /usr/lib/ruby/gems/1.8/gems/rspec-1.2.8/bin/spec:4
rake aborted!
Command /usr/bin/ruby.exe -I"/usr/lib/ruby/gems/1.8/gems/rspec-1.2.8/lib"  "/usr
/lib/ruby/gems/1.8/gems/rspec-1.2.8/bin/spec" "lib/spec/assemblyinfo_spec.rb" "l
ib/spec/assemblyinfotask_spec.rb" "lib/spec/msbuild_spec.rb" "lib/spec/msbuildta
sk_spec.rb" --colour --format specdoc failed
</code></pre>

**Comment by mxriverlynn** [comment]
turns out my issue running the tests from the source had nothing to do with running the gem... after installing the gem i figured out that the ; in the "/target:Clean;Build" parameter was being interpreted as a new command in cygwin bash. wrapping all parameters in quotes fixed that. the fix has been commited, so you should be able to get the latest source and run via cygwin now.

i'll open a new ticket for the issue i was having running the tests in cygwin (it's due to rake not playing well with rspec)
