### ISSUE TITLE
rename .command_directory to .working_directory

### ISSUE THREAD

**Issue by mxriverlynn** [mxriverlynn/Albacore#53]
in the RunCommand module, there is an option to set the working directory that the command is executed from. it's very poorly named: <code>.command_directory</code>

this should be changed to <code>.working_directory</code> or something else that makes it more obvious

**Comment by stevenharman** [comment]
this looks to be a small change, but I noticed the ncoverconsole task already has a working_directory method. After a quick glance it looks like that method basically passes the workingDirectory parameter on to the NCoverConsole executable, setting the directory from which the application is run.

That seems to be the basic functionality we're shooting for, but it's confusing having the one task in which this one option will have a different side effect. Thoughts?

**Comment by mxriverlynn** [comment]
yeah, that's the original reason i named it differently... i'm working on this right now, though. was going to see if the tests would pass by removing the one built into ncoverconsole task.

**Comment by mxriverlynn** [comment]
deleting the .working_directory from the ncoverconsole task worked. all tests are passing. the changes are in the dev branch.
