### ISSUE TITLE
ExpandTemplates should support hierarchical yaml

### ISSUE THREAD

**Issue by trullock** [mxriverlynn/Albacore#54]
Currently ExpandTemplates on supports top level yaml name/value pairs. It should support n-level deep configuration structures.

Also, why is it doing the tag replacement using regex instead of ERB?

here's a really quick hacked together replacement for the expand_templates method

http://gist.github.com/306492

**Comment by mxriverlynn** [comment]
irrelevant now that expandtemplates has been killed
