### ISSUE TITLE
need "complete" working examples

### ISSUE THREAD

**Issue by mxriverlynn** [mxriverlynn/Albacore#60]
need to create some example builds with albacore to show off the different features and capabilities, as blog posts and/or wiki pages, etc.

**Comment by nfisher** [comment]
Hi Derick,

I have something I've put together here;

https://github.com/JunctionBoxca/Rest-In-Practise-Product-Catalog-Service

It works on my local Win XP VM using the Windows 7.1 SDK.

Cheers,
Nathan

**Comment by haf** [comment]
I think there are enough of them around by now. Lots on my own github, MassTransit, FubuMVC, Castle.Transactions etc...

**Comment by mxriverlynn** [comment]
@haf - can you create a wiki page that links to the examples that you mentioned?

**Comment by haf** [comment]
Done.
