### ISSUE TITLE
store a list of folders in a hash for various tasks to use

### ISSUE THREAD

**Issue by mxriverlynn** [mxriverlynn/Albacore#66]
per this discussion: http://groups.google.com/group/albacoredev/msg/bae62866437a28df

support a hash of folders in the global config that can be referenced easily by the various tasks, making it easier to configure tasks to run external commands. 

still need some thought on implementation detail, and still consider scott's suggestion of using defaults per task, too. that would prevent users from having to specify the same folder for the same task, over and over again.

**Comment by stevenharman** [comment]
so is the the route we'd like to take for the msbuild version thing, rather than the 

```
msbuild :foobar do |msb|
  msb.version 4.0
  ...
end
```

route? I'm cool with whatever, was just looking to pick something up.

**Comment by mxriverlynn** [comment]
yeah, i think this is going to be a better way to go. take the same basic idea that you had and apply it across all of the tasks with folder names.

**Comment by mxriverlynn** [comment]
after putting in some working versions of this and then trying to use it in my rakefiles, i found it to be obtuse. it was easier and more straight forward to have my rakefile handle this more directly. so i'm scrapping it. to make the .net versions work, though, i have provided a simple way to configure the version of .net that is to be used through the global config:

<pre><code>Albacore.configure do |config|
  config.msbuild.use :net40
  config.csc.use :net35
</code></pre>


i know this is one of the things we originally thought about, and it turns out this was probably the right path. :)

this code exists in the dev branch already
