### ISSUE TITLE
kill the 'require_valid_command' setting in runcommand

### ISSUE THREAD

**Issue by mxriverlynn** [mxriverlynn/Albacore#68]
need to kill the .require_valid_command attribute in the RunCommand module. this option just causes problems. if someone wants to set the command exe to something that does not exist in the specified folder, they should be allowed to because it might be found in an environment PATH variable, etc.

**Comment by stevenharman** [comment]
killed with SHA: 1998536b8f93697bd82b3538109667461d56b976
