### ISSUE TITLE
MSpec runner throwing svn all-wcprops error after update

### ISSUE THREAD

**Issue by davetheninja** [mxriverlynn/Albacore#74]
UPDATE

Please ignore this issue, I have reverted back to 0.1.4 and the issue is continuing.

This is not an albacore issue

David

---

Hi Derick,

I have tried a few different things now to get the error to go away as I mentioned to you last night.

The MSpec runner is throwing the following error after running  a few tests - I have been trying to track down the root cause but am failing :-(

This is only since the upgrade to 0.1.5

David

Access to the path 'all-wcprops' is denied.
F, [2010-05-26T09:38:09.491046 #11800] FATAL -- : MSpec Failed. See Build Log For Detail
rake aborted!
MSpec Failed. See Build Log For Detail
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/albacore-0.1.5/lib/albacore/support/failure.rb:12:in `fail_with_message'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/albacore-0.1.5/lib/albacore/mspectestrunner.rb:39:in`execute'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/albacore-0.1.5/lib/rake/mspectask.rb:2
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/albacore-0.1.5/lib/rake/support/createtask.rb:17:in `call'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/albacore-0.1.5/lib/rake/support/createtask.rb:17:in`execute'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/albacore-0.1.5/lib/rake/support/albacoretask.rb:16
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`execute'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`execute'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
C:/Dev/project/tools/ruby/lib/ruby/1.8/monitor.rb:242:in`synchronize'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:607:in`invoke_prerequisites'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in `each'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in`invoke_prerequisites'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:596:in `invoke_with_call_chain'
C:/Dev/project/tools/ruby/lib/ruby/1.8/monitor.rb:242:in`synchronize'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:607:in`invoke_prerequisites'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in `each'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in`invoke_prerequisites'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:596:in `invoke_with_call_chain'
C:/Dev/project/tools/ruby/lib/ruby/1.8/monitor.rb:242:in`synchronize'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:607:in`invoke_prerequisites'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in `each'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in`invoke_prerequisites'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:596:in `invoke_with_call_chain'
C:/Dev/project/tools/ruby/lib/ruby/1.8/monitor.rb:242:in`synchronize'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:607:in`invoke_prerequisites'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in `each'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in`invoke_prerequisites'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:596:in `invoke_with_call_chain'
C:/Dev/project/tools/ruby/lib/ruby/1.8/monitor.rb:242:in`synchronize'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in`invoke'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in`top_level'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
C:/Dev/project/tools/ruby/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
C:/Dev/project/tools/ruby/bin/rake:19:in`load'
C:/Dev/project/tools/ruby/bin/rake:19

**Comment by hyrmn** [comment]
Hey Dave,
I know you ran into this a while ago, but I just ran into this issue with mspec too. For some reason, the new mspec creates a resources directory alongside the html report. If you don't notice that directory and check it in to svn, then mspec starts throwing a fit. Solution, delete the directory yourself and svn ignore it.
