### ISSUE TITLE
Cater for .NET 4 framework

### ISSUE THREAD

**Issue by PandaWood** [mxriverlynn/Albacore#76]
Albacore is hardcoded (in msbuild.rb) to .NET3.5
Should be settable/configurable to .NET4

**Comment by mxriverlynn** [comment]
currently, you can set the .path_to_command attribute to point msbuild to any location. several others have used this code to call out to .net 4:

<pre><code>msbuild :msbuild do |msb|
  msb.path_to_command = File.join(ENV['windir'], 'Microsoft.NET',
'Framework', 'v4.0.30319', 'MSBuild.exe')
  #... other settings here
end
</code></pre>


while it's not the optimal solution, it does provide a workaround for now. we are working on a better solution for the next major release, but there is no timeframe on it right now.

**Comment by mxriverlynn** [comment]
defaulted msbuild and csc to use .net 4 and made it easier to change .net versions through the global config settings. code is in the dev branch

**Comment by mxriverlynn** [comment]
when you want to switch .net versions, there are 3 ways to do this now

1: configuration. this sets the version for all instances of the msbuild task

<pre><code>Albacore.configure do |config|
  config.msbuild.use :net40
end
</code></pre>


2: override an individual instance

<pre><code>
msbuild :build do |msb|
  msb.use :net35
end
</code></pre>


3: set the command path and exe manually, with configuration or override for an instance. just use the <code>.command = "path/to/whatever"</code> attribute in either of the situations above.

of course, the default is now 4.0, so i'm showing these changing to .net 3.5
