### ISSUE TITLE
NDepend task fails because project file is not first on command line

### ISSUE THREAD

**Issue by PandaWood** [mxriverlynn/Albacore#78]
Ndepend.console.exe requires that the path to the project file is put first (1st) on the command line.
In the latest release (v0.1.5) this no longer happens, and it fails (I haven't fully investigated as to the cause of this)
For me, the project file is being placed last on the command line and results in a message:

"Bad command line arguments: Invalid option 'mypath/NDependProject.xml'

**Comment by PandaWood** [comment]
I've written a fix for this (with test) on my fork

**Comment by mxriverlynn** [comment]
these changes have been pulled into the dev branch
