### ISSUE TITLE
Check the .gemspec in so Albacore can be used with bundler

### ISSUE THREAD

**Issue by PandaWood** [mxriverlynn/Albacore#79]
Is there any reason the .gemspec for Albacore is not checked in as part of the source?

**Comment by mxriverlynn** [comment]
the gemspec is generated from the rakefile using jeweler, so there's no need to check it in with the source. if you want to generate it yourself, you can run this:

<code>rake jeweler:gemspec</code>

and if you want to build the gem from that gemspec:

<code>rake jeweler:build</code>

**Comment by PandaWood** [comment]
Oh, I see, thanks.
However, if you come to use 'bundler' - http://gembundler.com/ - you will start to see reasons to include the gemspec.
Bundler allows you to point to a specific gem via a github project. With albacore, with no explicit  gemspec, it doesn't work.
With all other github projects I know of, it does work, so I gather almost everyone else includes the gemspec (?). I don't know any other arguments for including it, so I'm just stating that one and leaving it at that.

**Comment by mxriverlynn** [comment]
ah - that's a fairly compelling reason, i think. i don't think it would hurt anything to keep the gemspec in the repo. i'll get that done

**Comment by mxriverlynn** [comment]
updated the dev branch to include the .gemspec file. this will be pushed into the master branch when 0.2.0 is released.
