### ISSUE TITLE
AssemblyInfo task: custom attributes not "custom" enough

### ISSUE THREAD

**Issue by e-tobi** [mxriverlynn/Albacore#90]
I need to add custom attributes like:

[assembly: XmlnsDefinition("http://www.acme.com", "Acme.Common.I18N")]

[assembly: XmlnsDefinition("http://www.acme.com", "Acme.Views.Helpers")]

This currently doesn't work because of two reasons:
1. Albacore doesn't allow to specify more than one attribute with the same way
2. Albacore doesn't allow to specify more than one attribute argument

I don't see a backwards-compatible solution here using custom_attributes, so I thought the simplest solution is to allow to define custom "raw" assembly info line:

asm.custom_data =  '[assembly: XmlnsDefinition("http://www.acme.com", "Acme.Common.I18N")]',
  '[assembly: XmlnsDefinition("http://www.acme.com", "Acme.Views.Helpers")]'

Feel free to pull:

http://github.com/e-tobi/Albacore/commit/e6b7d4c90786ba0d910b1e6e2da1f613feac78e1

**Comment by mxriverlynn** [comment]
ah - nice. i've never had to use multiple values in an attribute. i like the custom_data idea as a general "do whatever you need".

i think we can do some fun stuff with the existing custom_attributes to make it work, with only a little bit of code, too... i'm thinking something like this:

<pre><code>
  asm.custom_attributes :XmlnsDefinition => ["http://www.acme.com", "Acme.Common.I18N"]
</code></pre>


and then the assembly info task would know to spit out the array of values as the parameters to the attribute.

**Comment by e-tobi** [comment]
Yes, that was the first thing I did. Feel free to use my code, see the patch here:

http://pastie.org/1053830

I just threw this away again, because I couldn't find a nice way using custom_attributes to have multiple XmlnsDefinition attributes.

**Comment by e-tobi** [comment]
PS: Besides this, if you e.g. want to do:

```
[assembly: ThemeInfo(
    ResourceDictionaryLocation.None,
    ResourceDictionaryLocation.SourceAssembly
)]
```

...there's no way to specify ResourceDictionaryLocation.None right now. It must be provided as string, but shouldn't be quoted in the output.

What's also not possible is e.g.:

```
asm.copyright = "Copyright © 2010 ACME"
```

String.inspect() will escape the copyright sign, causing a syntax error.

So a "raw" custom_data can really be handy in such cases.

**Comment by mxriverlynn** [comment]
pulled the .custom_attributes code into the dev branch
