### ISSUE TITLE
add .trusted_connection to sqlcmd

### ISSUE THREAD

**Issue by mxriverlynn** [mxriverlynn/Albacore#91]
<pre><code>sqlcmd.trusted_connection = true</code></pre>

should set the <code>-E</code> option on the command line to force sqlcmd into trusted connection mode.

**Comment by brettveenstra** [comment]
Perhaps this should be the default behavior?

See http://github.com/brettveenstra/Albacore/blob/master/lib/albacore/sqlcmd.rb, Lines 26-30

**Comment by mxriverlynn** [comment]
i like that

**Comment by mxriverlynn** [comment]
your changes have been pulled into the dev branch.

**Comment by mxriverlynn** [comment]
a .trusted_connection attribute has been added. it is set to true by default. setting a username or password will override trusted_connection.
