### ISSUE TITLE
Allow commands to be specified relative to the project root

### ISSUE THREAD

**Issue by e-tobi** [mxriverlynn/Albacore#93]
I would like to do e.g. this:

```
nunit :run_tests => [:compile_release] do |nunit|
  nunit.command = 'libs/NUnit/bin/net-2.0/nunit-console-x86.exe'
  nunit.parameters '/framework=4.0', '/nothread', '/noshadow'
  nunit.working_directory = 'bin/Release'
```

It would be nice, if Albacore would be smart enough to see, that the provided command exists relative to the project root and would use exactly this executable.

Feel free to pull my solution:

http://github.com/e-tobi/Albacore/commit/7898df4a99ae51d84b7528a31562a7574c780725

**Comment by mxriverlynn** [comment]
pulled into the dev branch
