### ISSUE TITLE
SqlCmd does not report Failure if multiple files requested

### ISSUE THREAD

**Issue by brettveenstra** [mxriverlynn/Albacore#96]
SqlCmd needs to specifiy `-b` so any failure in the Batch results in a failure of the execution.

Perhaps this commit will do the trick: http://github.com/brettveenstra/Albacore/commit/75f35f14d80f1dac19b60114db35fe7020686637

**Comment by mxriverlynn** [comment]
i got this pulled in to the dev branch. there needs to be a way to turn off the -b option, though. that should be pretty easy to add. i'll see if i can get that done today.

**Comment by mxriverlynn** [comment]
can now add a <code>.batch_abort = false</code> to the sqlcmd configuration to disable this option.

**Comment by brettveenstra** [comment]
Sounds good.  I was enabling `-b` so that any failure in SqlCmd would fail the build.  Are you wanting to put a way to ignore SQL failures into SqlCmd?

**Comment by mxriverlynn** [comment]
basically, yes. the code is now set up so that it will add -b by default, when you have multiple sql scripts but it can be overridden by setting </code>.batch_abort = false</code>.
